#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

# Detect if the main display is the built-in laptop screen
MAIN_DISPLAY_INFO=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:')

if echo "$MAIN_DISPLAY_INFO" | grep -qi "built-in"; then
    source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
else
    source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
fi
