-- This file runs last in the AstroNvim setup process.
-- Transparency highlights live in plugins/astroui.lua (the supported
-- mechanism — survives :colorscheme changes, unlike one-shot :highlight).
